export const data=[
    {
      "addressId": 1,
      "project": {
        "projectId": 1,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 2,
      "project": {
        "projectId": 2,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 3,
      "project": {
        "projectId": 3,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 4,
      "project": {
        "projectId": 4,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 5,
      "project": {
        "projectId": 5,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 6,
      "project": {
        "projectId": 6,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 7,
      "project": {
        "projectId": 7,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 8,
      "project": {
        "projectId": 8,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 9,
      "project": {
        "projectId": 9,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 10,
      "project": {
        "projectId": 10,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 11,
      "project": {
        "projectId": 11,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 12,
      "project": {
        "projectId": 12,
        "projectTitle": "asdasd",
        "customerFirstName": "asdasdasd",
        "customerLastName": "asdasd",
        "customerPhoneNumber": 1231231231,
        "customerMobileNumber": 1231231231,
        "customerType": "business",
        "companyName": "sdfsdfsdf",
        "abnNumber": 123123,
        "gstRegistered": "yes"
      },
      "buildingName": "fdsfsdfsdf",
      "unitNumber": "12312312",
      "lotNumber": "123123",
      "streetNumber": "12312",
      "streetName": "asdasd1",
      "streetTypeSuffix": "123123",
      "suburb": "123123",
      "state": "NewSouthVales",
      "postcode": "123123"
    },
    {
      "addressId": 13,
      "project": {
        "projectId": 13,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 14,
      "project": {
        "projectId": 14,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 15,
      "project": {
        "projectId": 15,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 16,
      "project": {
        "projectId": 16,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 17,
      "project": {
        "projectId": 17,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 18,
      "project": {
        "projectId": 18,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 19,
      "project": {
        "projectId": 19,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 20,
      "project": {
        "projectId": 20,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 21,
      "project": {
        "projectId": 21,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 22,
      "project": {
        "projectId": 22,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 23,
      "project": {
        "projectId": 23,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 24,
      "project": {
        "projectId": 24,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 25,
      "project": {
        "projectId": 25,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 26,
      "project": {
        "projectId": 26,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 27,
      "project": {
        "projectId": 27,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 28,
      "project": {
        "projectId": 28,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 29,
      "project": {
        "projectId": 29,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 30,
      "project": {
        "projectId": 30,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 31,
      "project": {
        "projectId": 31,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 32,
      "project": {
        "projectId": 32,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 33,
      "project": {
        "projectId": 33,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 34,
      "project": {
        "projectId": 34,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 35,
      "project": {
        "projectId": 35,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 36,
      "project": {
        "projectId": 36,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 37,
      "project": {
        "projectId": 37,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 38,
      "project": {
        "projectId": 38,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 39,
      "project": {
        "projectId": 39,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 40,
      "project": {
        "projectId": 40,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 41,
      "project": {
        "projectId": 41,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 42,
      "project": {
        "projectId": 42,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 43,
      "project": {
        "projectId": 43,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 44,
      "project": {
        "projectId": 44,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 45,
      "project": {
        "projectId": 45,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 46,
      "project": {
        "projectId": 46,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 47,
      "project": {
        "projectId": 47,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 48,
      "project": {
        "projectId": 48,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 49,
      "project": {
        "projectId": 49,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 50,
      "project": {
        "projectId": 50,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 51,
      "project": {
        "projectId": 51,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 52,
      "project": {
        "projectId": 52,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 53,
      "project": {
        "projectId": 53,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 54,
      "project": {
        "projectId": 54,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 55,
      "project": {
        "projectId": 55,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 56,
      "project": {
        "projectId": 56,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 57,
      "project": {
        "projectId": 57,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 58,
      "project": {
        "projectId": 58,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 59,
      "project": {
        "projectId": 59,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 60,
      "project": {
        "projectId": 60,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 61,
      "project": {
        "projectId": 61,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 62,
      "project": {
        "projectId": 62,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 63,
      "project": {
        "projectId": 63,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 64,
      "project": {
        "projectId": 64,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 65,
      "project": {
        "projectId": 65,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 66,
      "project": {
        "projectId": 66,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 67,
      "project": {
        "projectId": 67,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 68,
      "project": {
        "projectId": 68,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 69,
      "project": {
        "projectId": 69,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 70,
      "project": {
        "projectId": 70,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 71,
      "project": {
        "projectId": 71,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 72,
      "project": {
        "projectId": 72,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 73,
      "project": {
        "projectId": 73,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 74,
      "project": {
        "projectId": 74,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 75,
      "project": {
        "projectId": 75,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 76,
      "project": {
        "projectId": 76,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 77,
      "project": {
        "projectId": 77,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 78,
      "project": {
        "projectId": 78,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 79,
      "project": {
        "projectId": 79,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 80,
      "project": {
        "projectId": 80,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 81,
      "project": {
        "projectId": 81,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 82,
      "project": {
        "projectId": 82,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 83,
      "project": {
        "projectId": 83,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 84,
      "project": {
        "projectId": 84,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 85,
      "project": {
        "projectId": 85,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 86,
      "project": {
        "projectId": 86,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 87,
      "project": {
        "projectId": 87,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 88,
      "project": {
        "projectId": 88,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 89,
      "project": {
        "projectId": 89,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 90,
      "project": {
        "projectId": 90,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 91,
      "project": {
        "projectId": 91,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 92,
      "project": {
        "projectId": 92,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 93,
      "project": {
        "projectId": 93,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 94,
      "project": {
        "projectId": 94,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 95,
      "project": {
        "projectId": 95,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    },
    {
      "addressId": 96,
      "project": {
        "projectId": 96,
        "projectTitle": "Pump",
        "customerFirstName": "Astha",
        "customerLastName": "Patel",
        "customerPhoneNumber": 9898989898,
        "customerMobileNumber": 98989898998,
        "customerType": "xyz",
        "companyName": "mojo365",
        "abnNumber": 123456,
        "gstRegistered": "45454545"
      },
      "buildingName": "abcd",
      "unitNumber": "123",
      "lotNumber": "10",
      "streetNumber": "5",
      "streetName": "ParkStreet",
      "streetTypeSuffix": "Park",
      "suburb": "pqr",
      "state": "MP",
      "postcode": "391700"
    }
  ];
  